### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by petermetz** [grasshopper/GWT-Setup#1]
Hiya,

I tried to compile the fresh checkout and failed to do it. I'm on Debian Wheeyz, Maven 3.0.4 and OpenJDK 1.7. 
See detailed error below:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.439s
[INFO] Finished at: Mon Jul 01 20:35:36 BST 2013
[INFO] Final Memory: 8M/88M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:1.2:generateAsync (default) on project gwtSetup: Execution default of goal org.codehaus.mojo:gwt-maven-plugin:1.2:generateAsync failed: syntax error @[13,2] in file:/home/peter/sw/GWT-Setup/src/main/java/com/coolisland/client/model/operation/Plus.java -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:1.2:generateAsync (default) on project gwtSetup: Execution default of goal org.codehaus.mojo:gwt-maven-plugin:1.2:generateAsync failed: syntax error @[13,2] in file:/home/peter/sw/GWT-Setup/src/main/java/com/coolisland/client/model/operation/Plus.java
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.codehaus.mojo:gwt-maven-plugin:1.2:generateAsync failed: syntax error @[13,2] in file:/home/peter/sw/GWT-Setup/src/main/java/com/coolisland/client/model/operation/Plus.java
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: com.thoughtworks.qdox.parser.ParseException: syntax error @[13,2] in file:/home/peter/sw/GWT-Setup/src/main/java/com/coolisland/client/model/operation/Plus.java
    at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:987)
    at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1293)
    at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:968)
    at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:317)
    at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:349)
    at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:345)
    at com.thoughtworks.qdox.JavaDocBuilder$2.visitFile(JavaDocBuilder.java:435)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:43)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan(DirectoryScanner.java:52)
    at com.thoughtworks.qdox.JavaDocBuilder.addSourceTree(JavaDocBuilder.java:432)
    at com.thoughtworks.qdox.JavaDocBuilder.addSourceTree(JavaDocBuilder.java:421)
    at org.codehaus.mojo.gwt.GenerateAsyncMojo.createJavaDocBuilder(GenerateAsyncMojo.java:340)
    at org.codehaus.mojo.gwt.GenerateAsyncMojo.execute(GenerateAsyncMojo.java:111)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    ... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by grasshopper** [comment]
I haven't touched this code in 3 years and I don't remember the details. Sorry.

**Comment by petermetz** [comment]
@grasshopper It's all good, thanks for responding! :-)
